--- https://postgresapp.com/


CREATE TABLE mytable(
   Club_Advisor_Form                               VARCHAR(30) 
  ,Club_Constitution                               VARCHAR(30)
  ,Club_Name                                       VARCHAR(48) NOT NULL PRIMARY KEY
  ,days                                             VARCHAR(10)
  ,Room                                            VARCHAR(15)
  ,Presidents_First_Name                           VARCHAR(18)
  ,Presidents_Last_Name                            VARCHAR(16)
  ,Presidents_Bronx_Science_Email                  VARCHAR(39)
  ,CoPresidentVice_Presidents_First_Name           VARCHAR(14)
  ,CoPresidentVice_Presidents_Last_Name            VARCHAR(15)
  ,CoPresidentsVice_Presidents_Bronx_Science_Email VARCHAR(30)
  ,Secretarys_First_Name                           VARCHAR(15)
  ,Secretarys_Last_Name                            VARCHAR(16)
  ,Secretarys_Bronx_Science_Email                  VARCHAR(30)
  ,Advisor_Names                                   VARCHAR(24)
  ,Advisors_Bronx_Science_Emails                   VARCHAR(43)
);
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'4-H','Thursdays','224','Victoria','Kim','kimv3@bxscience.edu','Chelsea','Li','lic10@bxscience.edu','Priscilla','Xu','xup@bxscience.edu','Ms. Perez','perez4@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'A Cappella','Friday','Cafe','Mollie','Ehrenberg','ehrenbergm@bxscience.edu','Katrina','Tablang','tablangk2@bxscience.edu','Nicole','Zhou','zhoun@bxscience.edu','Mr. McNickle','mcnickle@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Aerospace Club','Wednesday','031','Araf','Chowdhury','chowdhura10@bxscience.edu','Mansour','Doumbia','doumbiam@bxscience.edu','Joshua','Cammerman','cammermaj@bxscience.edu','Mr. Zanata','zanata@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Alive Poets Society','Friday','331','Pritish','Anand','anandp@bxscience.edu','Monica','Reilly','reillym@bxscience.edu',NULL,NULL,NULL,'Mr. McNickle','mcnickle@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Alternative Investment Club','Tuesday','320','Spencer','Silverman','silvermans@bxscience.edu','Zhen','Slew','siewz@bxscience.edu','Misbah','Uddin','uddinm@bxscience.edu','Ms.Kuan','Kuan@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'American Association for Foriegn Language Debate','Wednesday','321','Gabriela','Jimenez','jimenezg@bxscience.edu','Sabrina','Tiger','tigers@bxscience.edu','Esther','Gelman','gelmane@bxscience.edu','Sr. Uceda','uceda@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Amnesty International','Thursdays','207','Irene','Yimmongkol','yimmongkoli@bxscience.edu','Lucy','Chen','chenl12@bxscience.edu','Fatama','Islam','islamf1@bxscience.edu','Mr. McNickle','mcnickle@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Ancient Mythology Club','Thursday','213','Mahnez','Ahmed','ahmedm7@bxscience.edu','Davin','Dhanraj','dhanrajd@bxscience.edu','Jafnoon','Khatun','khatunj@bxscience.edu','Mr. Piccarella','piccarella1@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Asian American Association','Monday','231','Asuka','Koda','kodaa@bxscience.edu','Abigail','Choi','choia10@bxscience.edu','Saldon','Tenzin','tenzins@bxscience.edu','Mr. Temkin','temkin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'ASL Education Club','Wednesday','307','Ray','Nobuhara','nobuharar@bxscience.edu','Meshell','Peiris','peirism@bxscience.edu','Lena','Darby','darbyl@bxscience.edu','Ms. Macenulty','macenulty@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Astronomy Club','Tuesday','Planetarium/231','Camila','Kulahlioglu','kulahlioglue@bxscience.edu','David','Mushiyev','mushiyevd@bxscience.edu','Adrienne','Cui','cuia@bxscience.edu','Mr. Vanderpool','vanderpool@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Badminton Club','Tuesday','Courtyard','Mark','Kovrizhkin','kovrizhkm@bxscience.edu','Ena','Lu','lue@bxscience.edu','Alexander','Wong','wonga10@bxscience.edu','Ms. Jaitin','jaitin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Baking Club','Wednesday','337','Emily','Hsieh','hsiehe@bxscience.edu','Elisa','Chang','change1@bxscience.edu','Janine','Choy','choyj1@bxscience.edu','Ms. Coombs','coombs@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Best Buddies','Monday','334','Jemima','Eastwood','eastwoodj@bxscience.edu','Hannah','Nadler','nadlerh@bxscience.edu','Stella','Moelis','moeliss@bxscience.edu','Mr. DeSilva','desilva@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Bioethics','Monday','324','Esther','Gelman','gelmane@bxscience.edu','Chenxi','Lin','linc4@bxscience.edu','Chris','Procaccino','procaccic@bxscience.edu','Mr.Birnbaum','birnbaum@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Black and LatiNetwork','Wednesday','318','Ramesh','Perera-Olivo','perera-olivor@bxscience.edu','Ricardo','Espana','espanar@bxscience.edu','Paul','Petrovici Comrie','petrovicicomriep@bxscience.edu','Ms. Block','block@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Book Club','Monday','333','Tasnim','Hossain','hossaint4@bxscience.edu','Kristen','Li','lik6@bxscience.edu','Pithiya','D''Costa','dcostap@bxscience.edu','Mr. Birnbaum','birnbaum@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'BOSS/WIS','Tuesday','326','Gabriel','Wilson','Wilsone@bxscience.edu','Jadyn','Sinclar','sinclairj1@bxscienc.edu','Abrahim','Saho','sahoa@bxscience.edu','Ms.Mills','mills@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Bronx Science Hackers Club','Tuesday','006','Johanna','Stefanakis','stefanakisj@bxscience.edu','Aaron','Tang','tanga@bxscience.edu','Abdullah','Zidan','zidana@bxscience.edu','Mr.Zanata','zanata@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Bullet Journaling club','Monday','328','Nabiha','Chowdhury','chowdhuryn@bxscience.edu','Vedika','Jain','jainv@bxscience.edu',NULL,NULL,NULL,'Ms. Rosado','rosado2@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Business Society','Tuesdays','312','Carlissa','Satina','satinac2@bxscience.edu','Elisabeth','Langford','langforde@bxscience.edu','Yvonne','Wang','wangy11@bxscience.edu','Ms. Scotto','Scotto@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Cheer Club at Bronx Science','Thursday','008','Marinella','Ferrari-Bridgers','ferraribridgersm@bxscience.edu','Amidala','Barta-Zilles','bartazila@bxscience.edu','Rachel','Beckford','Beckfordr@bxscience.edu','Ms.Block','block@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Chinese Culture Club','Thursday','210','Lotus','Guo','guol@bxscience.edu','Xing Zhou','Xing Zhou','zhoux1@bxscience.edu','Sihui','Lin','lins18@bxscience.edu',NULL,NULL);
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Choreo Club','Thursday','Cafe','Sumi','Lama','lamas@bxscience.edu','Mritika','Rahman','rahmanm17@bxscience.edu','Cheryl','Lo','loc@bxscience.edu','Mr. Weng','weng1@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Club STAT','Tuesday','330','Tasmia','Afrin','afrint@bxscience.edu','Mahdher','Zaman','zamanm4@bxscience.edu','Harry','Troy','troyh@bxscience.edu','Ms. Chambers','chambers@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Comedy Club','Monday','124','Adam','Kamenetz','Kamenetza@bxscience.edu','Nitai','Huberman','hubermann@bxscience.edu','Luke','Ellerstein','ellersteinl@bxscience.edu','Mr. Hockert','hockert@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Computer Hardware Club','Thursday','031','Albert','Varela','varelaa@bxscience.edu','Yafang','Wu','wuy@bxscience.edu','Sean','Ham','hams2@bxscience.edu','Mr.Wala','wala@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Crafts for Humanity','Friday','331','Jasmine','Hwee','hweej@bxscience.edu','Junie','Chen','chenj@bxscience.edu','Meshell','Peiris','peirism@bxscience.edu','Mr. Chomet','chometm@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Currency Club','Monday','304','Matthew','Kaedav','kaedavm@bxscience.edu','Dimitrios',NULL,NULL,'Rahm','Rodkey','rodkeyr@bxscience.edu','Mr. Shibley','shibley@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Current Events Forum','Monday','310B','Mia','Zaslow','zaslowm@bxscience.edu','Sudiptha (Sud)','Paul','pauls2@bxscience.edu','Alliyana','Chan','chana13@bxscience.edu','Mr. Lubin','lubin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Cybersecurity and Ethical Hacking Club','Monday','231','Shaun','Karani','karanis@bxscience.edu','Taj','Jethwani-Keyser','jethwani-keysert@bxscience.edu','Demetrios','Gavalas','gavalasd@bxscience.edu','Mr. Iqbal','iqbala@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'DECA','Thursday','321','Yan','Li','liy@bxscience.edu','Yunxi','Wang','wangy9@bxscience.edu','Sarah','Sinoimeri','sinoimers@bxscience.edu','Mr.Bausili','bausili@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Desktop Robotics','Tuesday','31','Anthony','Wang','wanga16@bxscience.edu','Navil','Talukdar','talukdarn@bxscience.edu','Ryan','Mathew','mathewr@bxscience.edu','Ms. Ghaffar','ghaffar@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Digital Arts Club','Friday','303','Maria','Gil','gilm@bxscience.edu','Katherine','Han','Hank1@bxscience.edu','Mariam','Samake','samakem@bxscience.edu','Mr. Gonzowitz','gonzowitz@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'DoSomething Club','Wednesday','11','Taybah','Alam','alamt7@bxscience.edu','Justin','Wang','wangj13@bxscience.edu','Darien','Lu','lud4@bxscience.edu','Ms. Ferguson','ferguson@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Dungeons and Dragons Club','Wednesday','327','Daniel','Kim','kimd12@bxscience.edu','Peter','Neggie','neggiep1@bxscience.edu','Chanel','Champagnie','champagnc@bxscience.edu','Mr. Rodríguez','rodriguez@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Dynamo','Wednesday','207','Helen','Stone','stoneh@bxscience.edu','Lucia','Dec-Prat','dec-pratl@bxscience.edu','Arya','Eksambe','eksambea@bxscience.edu','Ms. Jaitin','jaitin@bxscience.Edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'East Asian Entertainment Club','Tuesday','315','Tasfia','Rahaman','rahamant@bxscience.edu','Kelly','Tching','tchingk@bxscience.edu','Elizabeth','Colon','colone@bxscience.edu','Ms. Block','block@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Economics Club','Monday','301','Winston','Le','lew@bxscience.edu','Abu','Ahmed','ahmeda10@bxscience.edu','Abdullah','Zidan','zidana@bxscience.edu','Ms. Meyer','meyer@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Edible Arts','Monday','337','Maitri','Sarkar','sarkarm@bxscience.edu','Henry','Yu','yuh2@bxscience.edu','Ethan','Rose','rosee@bxscience.edu','Ms.Coombs','coombs@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Engineering Club','Thursday','031','Mohadeb','Halder','halderm@bxscience.edu','Arka','Nath','Natha@bxscience.edu',NULL,NULL,NULL,'Mr.Wala','Wala@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Esports Club','Wednesday','227','Hannah','Yan','yanh@bxscience.edu','Sungroh','Ryu','ryus@bxscience.edu','Kaitlyn','Junas','junask@bxscience.edu','Mr.Weng','weng1@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Exposition','Wednesday','308','Ayana','Chari','charia@bxscience.edu','Regan','Toriello','toriellor@bxscience.edu','Nina','Mansfield','mansfieln@bxscience.edu','Mr.Fialkow','fialkow@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Film Production Club','Friday','318','Alvina','Rahman','rahmana13@bxscience.edu','Elisabeth','Chai','chaie@bxscience.edu','David','Wu','wud@bxscience.edu','Ms. Block','block@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Games Club','Thursday','231','Lola','Dong','dongl@bxscience.edu','Ka Tak','Tsoi','tsoik@bxscience.edu','Tiankuo','Zhang','zhangt5@bxscience.edu','Mr. Zanata','zanata@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Game Theory & Economics Society','Monday','111','Yan','Li','liy@bxscience.edu','Haoyue','Chen','chenh7@bxscience.edu','Yunxi','Wang','wangy9@bxscience.edu','Ms. Maylor','maylor@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Gardening Club','Friday','126','Ulises','Ponce','ponceu@bxscience.edu','Vera','Pankevich','pankevichv@bxscience.edu','Arianna','Hwang','hwanga3@bxscience.edu','Mr. Sarker','sarker@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Gender and Sexuality Alliance','Wednesday','315','Louisiana','Stahl','stahll@bxscience.edu','Kenae','Taylor','taylork@bxscience.edu','Ahmed','Hikmah','ahmeds14@bxscience.edu','Mr. Blessent','giorgisblessent@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Greek Club','Thursday','Cafe','Alessandra','Dounias','douniasa@bxscience.edu','Antonio','Velez','veleza@bxscience.edu','Ilias','Papageorgiou','papageorgioui@bxscience.edu','Ms. Berger','berger@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Green Team','Monday','031','Sudiptha (Sud)','Paul','pauls2@bxscience.edu','Anna','Hsu','hsua4@bxscience.edu','Shiya','Lin','lins10@bxscience.edu','Mr.Sarker &Mr. Harkert','sarker@bxscience.edu hockert@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Hindi Cinema Club (HCC)','Wednesday','222','Muntaha','Rashid','rashidm@bxscience.edu','Jafnoon','Khatun','khatunj@bxscience.edu','Angelina','Xie','xiea2@bxscience.edu','Ms.Berger','berger@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'History Club','Thursday','201','Matthieu','Choueiri','choueirim@bxscience.edu','Peter','Rooney','rooneyp@bxscience.edu','Kanae','Funabiki','funabikik@bxscience.edu','Mr. Shibley','shibley@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Horror Culture','Tuesday','310A','Lilly','Montelle','montellel@bxscience.edu','Stuti','Pardiwala','pardiwalas@bxscience.edu','Angelina','Xie','xiea2@bxscience.edu','Mr. Noody','noody@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'HOSA (Health Occupations Students of America)','Wednesday','130','Anindita','Das','dasa2@bxscience.edu','Lucia','Gallo','gallol@bxscience.edu','Edita','Cosovic','cosovice@bxscience.edu','Ms. Costanzo','costanzo@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Improv Club','Friday','336','Tallulah','Sarig','sarigt@bxscience.edu','Jasmine','Chen','Chenj28@bxscience.edu','Yardena','Franklin','Franklinj@bxscience.edu','Mr. McNickle','mcnickle@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Investment Society','Wednesday','105','Nittai','Hubermann','hubermann@bxscience.edu','Adam','Kamenetz','kamenetza@bxscience.edu','Steven','Chen','chens15@bxscience.edu','Ms. Pedraza','pedraza@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Italian Club','Thursday','210','Helena','Uceda','ucedah@bxscience.edu','Giulia','Cartegni','cartegnig@bxscience.edu','Lucia','Gallo','gallol@bxscience.edu',NULL,NULL);
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Japanese Animation Club','Wednesday','015','Malachi','Levinson','levinsonm@bxscience.edu',NULL,NULL,NULL,'Amanda','Widerka','widerkaa@bxscience.edu','Mr. Jonson','Jonson@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Jazz Club','Friday','334','Sittha','Cheerasarn','cheerasarns@bxscience.edu','Wynn','Chang','changw@bxscience.edu','Jayden','Singh','singhj@bxscience.edu','Mr. Grossman','grossman@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Jewish Student Union','Wednesday','307','Leona','Teten','tetenl@bxscience.edu','Gabrielle','Usvyat','usvyatg@bxscience.edu','Jordana','Franklin','franklinj@bxscience.edu','Mr. Fialkow','fialkow@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Journal of Biology','Thursday','331','Edita','Cosovic','cosovice@bxscience.edu','Natalie','Reid','reidn@bxscience.edu','Jessica','Singh','singhj1@bxscience.edu','Dr. LaGrassa','lagrassat@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Journal of Technology','Monday','003','Sinan','Roumie','roumies@bxscience.edu','Maisha','Fahmida','fahmidam@bxscience.edu','Jessica','Wang','wangj19@bxscience.edu','Mr. Fomin','fomin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Key Club','Thursday','336, 334','Shiya','Lin','lins10@bxscience.edu','Mandy','Lim','limm2@bxscience.edu','Chrissy','Jung','jungc2@bxscience.edu','Ms. Zareba & Mr.Rainford','zareba@bxscience.edu rainford@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Language Club','Thursdays','320','Dinah','Landsman','landsmand@bxscience.edu','Vincent','Harwood','harwoodv@bxscience.edu',NULL,NULL,NULL,'Ms Block','block@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Latin Club','Thursday','210','Lucia','Dec-Prat','dec-pratl@bxscience.edu','Isabelle','Na','nai1@bxscience.edu','Ray','Nobuhara','nobuharar@bxscience.edu',NULL,NULL);
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'League of Environmental and Animal Protection','Tuesday','307','Jonathon','Lee','leej13@bxscience.edu','Pithiya','D''Costa','dcostap@bxscience.edu','Emma','Chi','chie@bxscience.edu','Ms.Chambers','chambers@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Legal Society','Monday','319','Charlotte (Zhiyou)','Zhou','zhouz@bxscience.edu','Ayshi','Sen','sena@bxscience.edu','Ava','Conner','connera@bxscience.edu','Ms. Block','block@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Lunar New Year Productions','Wednesday','Cafe','Jialing','Liu','liuj13@bxscience.edu','Linh','Liu','luul@bxscience.edu','Hubert','Cao','caoh@bxscience.edu','Ms. Davis','davis1@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Makerspace','Thursday','031','Mohadeb','Halder','Halderm@bxscience.edu','Arika','Nath','Natha@bxscience.edu','Anthony','Wang','Wanga16@bxscience.edu','Mr. Wala','Wala@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Martial Arts Culture Club','Monday','008/Vestibule B','Jayden','Tom','tomj@bxscience.edu','Joshua','Choy','choyj@bxscience.edu','Franklin','Tjong','tjongf@bxscience.edu','Mr. Chomet','chometm@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Math Bulletin','Friday','006','Shaun','Karani','karanis@bxscience.edu','Steven','Teh','tehs2@bxscience.edu',NULL,NULL,NULL,'Dr. Shapovalov','shapovalov@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Math Club','Friday','005','Chrissy','Jung','jungc2@bxscience.edu','Mark','Kovrizhkin','kovrizhkm@bxscience.edu','Aaron','Kim','kima13@bxscience.edu','Mr. Fomin','fomin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Mental Health Association','Wednesday','331','Tasmia','Afrin','afrint@bxscience.edu','Siddratul','Moonthaha','moonthahas@bxscience.edu','Grace','Lin','ling@bxscience.edu','Max Chomet','chometm@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Modern Music Appreciation','Wednesday','310B','Sudiptha (Sud)','Paul','pauls2@bxscience.edu','James','Yao','yaoj2@bxscience.edu','Madalee','Weissman','weissmanm@bxscience.edu','Mr. Saviano','savaiano@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Multicultural Club','Monday','231','Asuka','Koda','kodaa@bxscience.edu','Gil','Friedman','friedmang@bxscience.edu','Malena','Galletto','gallettom@bxscience.edu','Mr. Temkin','Temkin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Music Technology Club','Tuesday','332','Braden','Lenn','lennb@bxscience.edu','Sittha','Cheerasan','cheerasans@bxscience.edu','Lilly','Montelle','montellel@bxscience.edu','Mr. DeSilva','desilva@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Muslim Students'' Association','Wednesday','319','Humairah','Chowdhury','chowdhuryh@bxscience.edu','Zabed','Iqbal','iqbalz2@bxscience.edu','Shad','Talha','talhas@bxscience.edu','Ms. Rubio','rubio@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'NASHA of Culture Club','Thursday','319','Mahzabin','Ahmed','ahmedm8@bxscience.edu','Fairuz','Raya','rayaf@bxscience.edu','Mysha','Rahman','rahmanm18@bxscience.edu','Ms. Rubio','rubio@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'National Organization for Women','Wednesday','311','Regan','Toriello','toriellor@bxscience.edu','Olivia','Girand','girando@bxscience.edu','Sophia','Markens','markenss@bxscience.edu','Ms. MacEnulty','macenulty@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Paper Crafts (ARTS CLUB)','Tuesday','211','Natalie','Eng','engn@bxscience.edu','Ayshi','Sen','sena@bxscience.edu','Zihan','Wang','wangz2@bxscience.edu','Ms. Kennedy','kennedy2@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Pathogenesis Research Club','Thursday','325','Subah','Mehrin','mehrins@bxscience.edu','Fabiha','Chowdhury','chowdhurf@bxscience.edu','Subat','Rodoshe','rodoshes@bxscience.edu','Dr. Lagrassa','lagrassat@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Photography Club','Thursday','212','Tristan','Borlongan','borlongat@bxscience.edu','Abigail','Choi','choia10@bxscience.edu','Maliha','Chowdhury','chowdhurm5@bxscience.edu','Trek Martin','martin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Podcast Club','Wednesday','312B','Saldon','Tenzin','tenzins@bxscience.edu','Vivian','Zou','zouv2@bxscience.edu','Jazmine','Pawar','pawarj@bxscience.edu','Mr.Martin','Martin@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Pokemon Appreciation Club','Thursday','226','Kaitlyn','Junas','junask@bxscience.edu','Isaac','Wang','wangi2@bxscience.edu','Saajid','Rohman','rohmans@bxscience.edu','Mr. Scheiber','scheiber@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Political Discourse Club: Leftist Theory','Wednesday','315','Karishma','Ramkarran','Ramkarrank@bxscience.edu','Parker','Brandenburg','Brandenburgp@bxscience.edu','Laszlo','Stein','steinl@bxscience.edu','Mr. Blessent','Giorgisblessent@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Pre-Medical Society','Wednesday','336','Sarah','Cheng','chengs3@bxscience.edu','Pithiya','D''Costa','dcostap@bxscience.edu','Jonathan','Lin','linj22@bxscience.edu','Dr. LaGrassa','lagrassat@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Psych and Neuro Club','Thursday','326','Alice','Elliott','elliotta@bxscience.edu','Kiele','Morgan','morgank@bxscience.edu','Yueyang (Derek)','Dong','dongy@bxscience.edu','Dr. LaGrassa','lagrassat@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Public Health and Biostatistics Club','Monday','233','Umme','Anushka','anushkau@bxscience.edu','Humairah','Chowdhury','chowdhuryh@bxscience.edu','Harry','Troy','troyh@bxscience.edu','Erin O''Leary','oleary@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Quizbowl','Monday','306','Lucas','Melendez','melendezl@bxscience.edu','Emma','Byron','byronp@bxscience.edu','Peter','Ballas','ballasp@bxscience.edu','Mr.Symons','symons@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Real World Finance','Friday','Cafe','Aman','Keshwani','keshwania@bxscience.edu','Tyler','Liang','liangt@bxscience.edu','John','Metis','metisj@bxscience.edu','Ms. Block','block@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Science Theory Club','Monday','233','Edita','Cosovic','cosovice@bxscience.edu','Dredheza','Gashi-Baraliu','gashi-baraliud@bxscience.edu','Manuel','Bosteels','bosteelsm@bxscience.edu','Dr. O''Leary','oleary@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Slavic Culture Club','Friday','233','Maks','Coven','covenm@bxscience.edu','Myles','Coven','covenm1@bxscience.edu','Ali','Hamlani','hamlania@bxscience.edu','Mr. Lee','lee@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Sports Debate Club','Wednesday','103','Max','Tsigalnitsky','tsigalnim@bxscience.edu','Ethan','Weinberg','weinberge@bxscience.edu','Baila','Diallo','diallob2@bxscience.edu','Mr. Elia','elia@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Sports Fitness Club','Tuesday','Courtyard','Suraiya','Suri','suris@bxscience.edu','Grace','Zagoria','zagoriag@bxscience.edu','Donna','Celentano','celentanod@bxscience.edu','Ms. Brooks','brooks@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Starving Artists Society','Thursday','208','Angelina','Xie','xiea2@bxscience.edu','Muntaha','Rashid','rashidm@bxscience.edu','Sumaiya','Jessi','jessis@bxscience.edu','Ms. Scotto','scotto@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'STRIDES','Thursday','328','Zubayer','Mahbub','mahbubz@bxscience.edu','Moontachier','Taseen','taseenm@bxscience.edu','Anindita','Das','dasa2@bxscience.edu','Dr. LaGrassa','lagrassat@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'The Green Room','Wednesday','212','Dinah','Landsman','landsmand@bxscience.edu','Vincent','Harwood','harwoodv@bxscience.edu','Katia','Anastas','anastask@bxscience.edu','Mr. Bausili','bausili@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'UNICEF','Wednesday','202','Krishti','Banik','banikk@bxscience.edu','Jessica','Wang','wangj19@bxscience.edu','Suri','Lin','lins12@bxscience.edu','Ms. Lewis','lewis@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Visual Novel Club','Friday','127','Jiuk','Park','parkj10@bxscience.edu','Mostafa','Daiyam','daiyamm@bxscience.edu','Javier','Vasquez','vasquezj@bxscience.edu','Mr. Zanata','zanata@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Vivo Latino','Thursday','110','Genesis','Sanchez','sanchezmedinag@bxscience.edu','Stefan','Inderbitzin','Inderbitzins@bxscience.edu','Paule Jena','Silatchom','silatchomp@bxscience.edu','Ms. Perez','perez4@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Vox Discipulorum','Thursday','313','Jakin','Chen','chenj23@bxscience.edu','Cheng Lin','Qiao','qiaoc@bxscience.edu','Anthony','Long','longa@bxscience.edu','Mr. Qiu','Qiu@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Young Democrats','Wednesday','313','Jemima','Eastwood','eastwoodj@bxscience.edu','Sophie','Grossman','grossmans@bxscience.edu','Finley','Heesch','heeschf@bxscience.edu','Mr. Blessent','giorgisblessent@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Ultimate Frisbee','Wednesday','Cafe','Vincent','Harwood','harwoodv@bxscience.edu','Oscar','De Swaan Aarons','deswaanaronso@bxscience.edu','Eliot','Levin','levine2@bxscience.edu','Mr.Liang','Liang@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'MUN','Tuesday','131','Vincent','Harwood','harwoodv@bxscience.edu','Matthew','Kadaev','kadaevm@bxscience.edu','Matthieu','Choueiri','choueirim@bxscience.edu','Ms. Macenulty','macenulty@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'SciOly','Wednesday','Various','Matthew','Kadaev','kadaevm@bxscience.edu',NULL,NULL,NULL,NULL,NULL,NULL,'Ms. Womer, Ms. Nichols','womer@bxscience.edu, nichols@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Speech & Debate','M-Thurs','Various','Leadership',NULL,'speechanddebateleadership@bxscience.edu',NULL,NULL,NULL,NULL,NULL,NULL,'Mr. Huth','huth@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'S!NG','Mon/Wed','Aud','Kelly','Tching','tchingk@bxscience.edu','Vivian','Lin','linv6@bxscience.edu',NULL,NULL,NULL,'Ms. Williams','williams@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'Robotics','Mon/Wed','004, 006','Bella','Pensabene','pensabenei@bxscience.edu','Nicholas','Gavalas','gavalasn@bxscience.edu',NULL,NULL,NULL,'Mr. Ilany, Mr. Morrell','ilany@bxscience.edu, morrell@bxscience.edu');
INSERT INTO mytable(Club_Advisor_Form,Club_Constitution,Club_Name,days,Room,Presidents_First_Name,Presidents_Last_Name,Presidents_Bronx_Science_Email,CoPresidentVice_Presidents_First_Name,CoPresidentVice_Presidents_Last_Name,CoPresidentsVice_Presidents_Bronx_Science_Email,Secretarys_First_Name,Secretarys_Last_Name,Secretarys_Bronx_Science_Email,Advisor_Names,Advisors_Bronx_Science_Emails) VALUES (NULL,NULL,'REACTIONS','Mon 10th','224','Julianne','Lee','leej14@bxscience.edu','Rebecca','Xie','xier@bxscience.edu',NULL,NULL,NULL,'Ms. Ghaffar','ghaffar@bxscience.edu');

SELECT * FROM mytable;

CREATE TABLE student_users(
First_Name                               VARCHAR(30) 
  ,Last_Name                               VARCHAR(30)
  ,email                                       VARCHAR(48) NOT NULL PRIMARY KEY
  ,osis                                             VARCHAR(15)
  ,secret                                           VARCHAR(15)
  ,grad_year                           VARCHAR(4)
  );
  INSERT INTO student_users (First_Name, Last_Name, email, osis, secret, grad_year)
      VALUES ('Sneha', 'Das', 'dass3@bxscience.edu', '221148885', 'password', '2023');
      
SELECT * FROM student_users;
